# Generated by Django 3.0.4 on 2022-12-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dci',
            name='is_active',
        ),
    ]
