# Generated by Django 3.0.4 on 2022-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_dci_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dci',
            name='code',
            field=models.CharField(blank=True, default='DCI0001', max_length=255, null=True),
        ),
    ]
